### ISSUE TITLE
transaction tracing: not working

### ISSUE THREAD

**Issue by vmarchaud** [keymetrics/trassingue#3]
@Unitech commented on [Fri Sep 15 2017](https://github.com/keymetrics/km-api/issues/349)

```
TypeError: Cannot redefine property: stream -
at Function.defineProperty ()
at RedisClient.create_stream_trace (/home/ubuntu/node_modules/vxx/src/plugins/plugin-redis.js:36:16)
at RedisClient.create_stream_trace [as create_stream] (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/plugins/plugin-redis.js:44:28)
at new RedisClient (/home/ubuntu/node_modules/redis/index.js:161:10)
at exports.createClient (/home/ubuntu//node_modules/redis/index.js:1081:12)
at createClientTrace (/home/ubuntu/node_modules/vxx/src/plugins/plugin-redis.js:24:33)
at createClientTrace (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/plugins/plugin-redis.js:24:33)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Function.Module_load (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/trace-plugin-loader.js:168:33)
at Function. (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
at Function.Module_load (/home/ubuntu/node_modules/vxx/src/trace-plugin-loader.js:168:33)
```

```
TypeError: newSpan.addLabels is not a function 
at TraceAgent.startSpan (/usr/lib/node_modules/pmx/node_modules/vxx/src/trace-agent.js:109:13) 
at TraceApiImplementation.createChildSpan (/usr/lib/node_modules/pmx/node_modules/vxx/src/trace-api.js:187:36) 
at TraceApi.createChildSpan (/usr/lib/node_modules/pmx/node_modules/vxx/src/trace-api.js:293:19) 
at Client.query_trace [as query] (/usr/lib/node_modules/pmx/node_modules/vxx/src/plugins/plugin-pg.js:29:26) 
at /code/cc-api/app/models/thera/cc_register_subject.js:29:20 
at Connection. (/code/cc-api/app/node_modules/pg/lib/client.js:158:7) 
at Connection.g (events.js:291:16) 
at emitOne (events.js:101:20) 
at Connection.emit (events.js:188:7) 
at Socket. (/code/cc-api/app/node_modules/pg/lib/connection.js:121:12)
```

https://keymetrics.zendesk.com/agent/tickets/1210

```
We're having an issue with Transaction Tracing: We see the following error when we load the page:

http://i.theleague.com/2Q0V2B2z3M2R

{"msg":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[qUf85ND_QDKd9w6CfiIs1Q][x6xhylzxfrhd4dy][0]: RemoteTransportException[[Angler][inet[/10.91.214.36:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }{[qUf85ND_QDKd9w6CfiIs1Q][x6xhylzxfrhd4dy][1]: RemoteTransportException[[Angler][inet[/10.91.214.36:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }{[y2Pm5wCETS-95jYsop1LsA][x6xhylzxfrhd4dy][2]: RemoteTransportException[[Behemoth][inet[/10.91.214.25:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }]"}
```

https://keymetrics.zendesk.com/agent/tickets/1407

**Comment by arpithparikh** [comment]
any update on this issue?
